jobs:
  test:
    docker:
      - image: circleci/node:14
      - image: circleci/mongo:4.4
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
      - run:
          command: NODE_ENV=test PORT=8081 npm run test
orbs:
  node: circleci/node@4.1.0

version: 2.1

workflows:
  test_my_app:
    jobs:
      - test