version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  test:
    steps:
      - checkout
      - node/install-packages
      - run:
          name: compile-tsc
          command: npm run build
      - run:
          name: test
          command: NODE_ENV=test PORT=8081 npm run test
    docker:
      - image: circleci/node:14
      - image: circleci/mongo:4.4